calendar
js-tasks-ru/htmlcss-20230124_sharkbalik pull request #10
Opened 2023-02-13 16:24 UTC by Kopekbalik

2023-02-13 16:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 10:44 UTC, GSemikozov requested changes

2023-02-14 10:44 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar_title {
просьба поправить имена всех элементов - элементы в БЭМ пишем через 2 нижних подчеркивания

2023-02-14 13:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 13:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-10 14:22 UTC, GSemikozov approved these changes

2023-04-10 14:22 UTC, merged