background
js-tasks-ru/htmlcss-20230124_sharkbalik pull request #14
Opened 2023-04-06 12:49 UTC by Kopekbalik

2023-04-06 12:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-08 11:16 UTC, GSemikozov requested changes

2023-04-08 11:16 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +body {
насколько помню, смысл задания был в том, чтобы сделать фон адаптивный - то есть в зависимости от ширины экрана менять картинку)

2023-04-12 22:29 UTC, GSemikozov approved these changes

2023-04-12 22:29 UTC, merged