не получилось проверить X2
js-tasks-ru/htmlcss-20230124_sharkbalik pull request #15
Opened 2023-04-06 13:29 UTC by Kopekbalik

2023-04-06 13:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-08 11:18 UTC, GSemikozov requested changes

2023-04-08 11:18 UTC, GSemikozov commented on 06-lection4/03-srcset/index.html
> +            <img class="avatar__img" src="./public/forest_400.jpg" sizes=""srcset="./public/forest_768.jpg 2x" alt="" >
srcset="./public/forest_400.jpg 1x, ./public/forest_768.jpg 2x"

2023-04-08 11:18 UTC, GSemikozov commented on 06-lection4/03-srcset/index.html
> +            <img class="avatar__img" src="./public/forest_400.jpg" sizes=""srcset="./public/forest_768.jpg 2x" alt="" >
<img width="625" alt="Screenshot 2023-04-08 at 14 17 28" src="https://user-images.githubusercontent.com/6191270/230718282-b457e6af-666a-4c61-879d-6e440ec87de6.png">
вот как можно проверять плотность пикселей
<img width="82" alt="Screenshot 2023-04-08 at 14 17 55" src="https://user-images.githubusercontent.com/6191270/230718305-827a1695-f553-4704-93b1-0f28c1d6d430.png">

2023-04-10 07:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-10 08:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-18 08:07 UTC, GSemikozov approved these changes

2023-04-18 08:07 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-04-18 08:08 UTC, GSemikozov approved these changes

2023-04-18 08:08 UTC, merged