histogram попытка 1
js-tasks-ru/htmlcss-20230124_sharkbalik pull request #6
Opened 2023-02-06 09:00 UTC by Kopekbalik

2023-02-06 09:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-06 09:50 UTC, GSemikozov requested changes

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +a {
глобальные стили в файле стилей конкретного компонента не описываем (если это глобальный сброс -> normalize, если локальный - то в конкретном классе элемента блока)

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +height: 141px;
лишнее ограничение

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +width: 310px;
и здесь

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_more {
здесь и ниже - элементы по БЭМ пишутся через 2 нижних подчеркивания, а модификаторы - через 1

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.scale_full {
.histogram__chart-line - основные стили, высота - через модификаторы по типу .histogram__chart-line_full

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
ширину лучше задавать через flex-basis + использовать flex-grow: 1 (проверить ситуацию когда в чарте может быть всего 1-2 колонки)

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_more {
вообще это лишний модификатор - это базовые стили всего блока

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_block {
.histogram__header

2023-02-06 09:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_item {
.histogram__headings / .histogram__info etc

2023-02-06 18:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-07 09:49 UTC, GSemikozov requested changes

2023-02-07 09:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 81px;
39

2023-02-07 09:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 117px;
ого) нет, это лишнее.

2023-02-07 09:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 9px;
+ flex-grow: 1;

2023-02-07 09:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-grow: 1;
flex-grow удалить из всех модификаторов

2023-02-07 12:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 10:40 UTC, GSemikozov requested changes

2023-02-14 10:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-left: 144px;
удалим (выравнивать надо через родителя который у нас флекс-контейнер)

2023-02-14 10:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 81px;
все еще актуально

2023-04-12 22:30 UTC, GSemikozov requested changes

2023-04-12 22:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 39px;
было правильно, надо вернуть 50

2023-04-12 22:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> -display: inline-block;
было правильно

2023-04-12 22:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +width: 350px;
а это лишнее

2023-04-18 08:06 UTC, GSemikozov approved these changes

2023-04-18 08:06 UTC, merged